version: '3.8'
services:
  database:
    container_name: database
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'oipie'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'oipie'