spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: oipie
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
      show-sql: false
    show_sql: false
test:
  clockService: true
  uuidService: true