spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialize: true
    continue-on-error: true
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password:  ${DB_PASSWORD}
    platform: postgres
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: false
    show_sql: false
  liquibase:
    enabled: false